### ISSUE TITLE
Login Fails

### ISSUE THREAD

**Issue by Clicksurfer** [nirizr/timewatch#10]
Hi, first of all - thanks for creating this script. I understand it's no longer being maintained but perhaps some good samaritan can help me :)

Running the script seems to work, but the login operation fails. Obviously I can't share my login info, but the parameters I put into the script seem to be correct.
People who are using this script - does your login fail as well? Have you found a potential fix for it?

Error I get:

`Traceback (most recent call last):
  File "C:\Dev\timewatch\timewatch\main.py", line 48, in <module>
    tw.login(args.company, args.user, args.password)
  File "C:\Dev\timewatch\timewatch\timewatch.py", line 76, in login
    raise TimeWatchException("Login failed!")
timewatch.TimeWatchException: Login failed!
`

**Comment by edengbigabid** [comment]
I also got the timewatch.TimeWatchException: Login failed!

**Comment by tobenary** [comment]
https://github.com/tobenary/timewatch_slack_filler

Instead of the Slack bot, use the main time watch.
